// SPDX-License-Identifier: ekubo-license-v1.eth
pragma solidity =0.8.33;

import {Test} from "forge-std/Test.sol";
import {ICore} from "../../src/interfaces/ICore.sol";
import {Core} from "../../src/Core.sol";
import {MEVCaptureV21Harness} from "./MEVCaptureV21Helpers.sol";
import {MEVCaptureV21PoolState, createMEVCaptureV21PoolState} from "../../src/types/mevCaptureV21PoolState.sol";

/// @notice Checks the contract's rules against the vectors in test/data/mevcapture-v21, generated by the exact Python
///   model (test/extensions/mevcapture-v21/gen_vectors.py), which is itself cross-checked against the design models
///   v23_gate_model.py (gate, H1) and v21_attacks.py (segment schedule).
contract MEVCaptureV21VectorsTest is Test {
    struct St {
        int256 anchorX16;
        uint256 lRefBits;
        uint256 lRefRaiseTime;
        uint256 lRefTime;
        uint256 lastPosTime;
        uint256 lastUpdateTime;
        uint256 snapBits;
    }

    struct Step {
        string op;
        uint256 timestamp;
        int256 tick;
        uint256 liquidity;
        uint256 liquidityAfter;
        uint256 activeLiquidity;
        bool first;
        bool passed;
        uint256 lObs;
        uint256 eRef;
        St expected;
    }

    struct Update {
        St stateIn;
        int256 tick;
        uint256 liquidity;
        uint256 timestamp;
        bool passed;
        uint256 lObs;
        uint256 eRef;
        St expected;
    }

    struct Seg {
        uint256 k;
        int256 loX16;
        int256 hiX16;
        int256 hiTick;
        uint256 fee;
    }

    struct Schedule {
        uint256 jLin;
        uint256 poolFee;
        uint256 spacingExp;
        int256 anchorX16;
        bool increasing;
        int256 coreTick;
        int256 towardTick;
        Seg[] segments;
    }

    string internal constant ST =
        "St(int256 anchorX16,uint256 lRefBits,uint256 lRefRaiseTime,uint256 lRefTime,uint256 lastPosTime,uint256 lastUpdateTime,uint256 snapBits)";
    string internal constant DIR = "test/data/mevcapture-v21/";

    MEVCaptureV21Harness internal h16;
    MEVCaptureV21Harness internal h64;

    function setUp() public {
        ICore core = new Core();
        h16 = new MEVCaptureV21Harness(core, 120, 4, 0, 16, 1 << 15, 2500, 3);
        h64 = new MEVCaptureV21Harness(core, 120, 4, 0, 64, 1 << 15, 2500, 3);
    }

    function _pack(St memory s) internal pure returns (bytes32) {
        return MEVCaptureV21PoolState.unwrap(
            createMEVCaptureV21PoolState({
                _lastUpdateTime: uint32(s.lastUpdateTime),
                _lRefTime: uint32(s.lRefTime),
                _lastPosTime: uint32(s.lastPosTime),
                _lRefBits: uint8(s.lRefBits),
                _snapBits: uint8(s.snapBits),
                _lRefRaiseTime: uint32(s.lRefRaiseTime),
                _anchorX16: int64(s.anchorX16)
            })
        );
    }

    function test_vectors_gate_scenarios() public view {
        string memory json = vm.readFile(string.concat(DIR, "gateScenarios.json"));
        uint256 n = abi.decode(vm.parseJson(json, ".gateScenarios"), (bytes[])).length;
        assertGt(n, 0);
        uint256 steps;
        for (uint256 i; i < n; i++) {
            string memory base = string.concat(".gateScenarios[", vm.toString(i), "]");
            St memory init = abi.decode(vm.parseJsonType(json, string.concat(base, ".initial"), ST), (St));
            Step[] memory ss = abi.decode(
                vm.parseJsonTypeArray(
                    json,
                    string.concat(base, ".steps"),
                    string.concat(
                        "Step(string op,uint256 timestamp,int256 tick,uint256 liquidity,uint256 liquidityAfter,uint256 activeLiquidity,bool first,bool passed,uint256 lObs,uint256 eRef,St expected)",
                        ST
                    )
                ),
                (Step[])
            );
            bytes32 state = _pack(init);
            for (uint256 j; j < ss.length; j++) {
                Step memory st = ss[j];
                uint32 t = uint32(st.timestamp);
                if (keccak256(bytes(st.op)) == keccak256("position")) {
                    state = h16.snapshot(state, uint128(st.activeLiquidity), t);
                } else {
                    if (st.first) {
                        bool passed;
                        uint256 lObs;
                        uint256 eRef;
                        (state, passed, lObs, eRef) = h16.anchorUpdate(state, int32(st.tick), uint128(st.liquidity), t);
                        assertEq(passed, st.passed, "passed");
                        assertEq(lObs, st.lObs, "lObs");
                        assertEq(eRef, st.eRef, "eRef");
                    } else {
                        assertEq(MEVCaptureV21PoolState.wrap(state).lastUpdateTime(), t, "not first");
                    }
                    state = h16.refresh(state, uint128(st.liquidityAfter), t);
                }
                assertEq(state, _pack(st.expected), "state after step");
                steps++;
            }
        }
        assertGt(steps, 1000);
    }

    function test_vectors_anchor_updates() public view {
        string memory json = vm.readFile(string.concat(DIR, "anchorUpdates.json"));
        Update[] memory us = abi.decode(
            vm.parseJsonTypeArray(
                json,
                ".anchorUpdates",
                string.concat(
                    "Update(St stateIn,int256 tick,uint256 liquidity,uint256 timestamp,bool passed,uint256 lObs,uint256 eRef,St expected)",
                    ST
                )
            ),
            (Update[])
        );
        assertEq(us.length, 120);
        for (uint256 i; i < us.length; i++) {
            Update memory u = us[i];
            (bytes32 next, bool passed, uint256 lObs, uint256 eRef) =
                h16.anchorUpdate(_pack(u.stateIn), int32(u.tick), uint128(u.liquidity), uint32(u.timestamp));
            assertEq(passed, u.passed, "passed");
            assertEq(lObs, u.lObs, "lObs");
            assertEq(eRef, u.eRef, "eRef");
            assertEq(next, _pack(u.expected), "state");
        }
    }

    function test_vectors_schedules() public view {
        string memory json = vm.readFile(string.concat(DIR, "schedules.json"));
        Schedule[] memory ss = abi.decode(
            vm.parseJsonTypeArray(
                json,
                ".schedules",
                "Schedule(uint256 jLin,uint256 poolFee,uint256 spacingExp,int256 anchorX16,bool increasing,int256 coreTick,int256 towardTick,Seg[] segments)Seg(uint256 k,int256 loX16,int256 hiX16,int256 hiTick,uint256 fee)"
            ),
            (Schedule[])
        );
        assertEq(ss.length, 288);
        uint256 segs;
        for (uint256 i; i < ss.length; i++) {
            Schedule memory sc = ss[i];
            MEVCaptureV21Harness h = sc.jLin == 64 ? h64 : h16;
            (int256[] memory his, uint256[] memory fees, uint256 firstK) = h.segments(
                int64(sc.anchorX16),
                sc.increasing,
                int32(sc.coreTick),
                sc.poolFee,
                uint8(sc.spacingExp),
                sc.segments.length
            );
            assertEq(firstK, sc.segments[0].k, "first segment");
            for (uint256 j; j < his.length; j++) {
                assertEq(his[j], sc.segments[j].hiX16, "boundary");
                assertEq(fees[j], sc.segments[j].fee, "fee");
            }
            // toward call end: floor (increasing) or ceil (decreasing) of the anchor, as in the contract
            int256 a = sc.increasing ? sc.anchorX16 : -sc.anchorX16;
            int256 tt = a >> 16;
            assertEq(sc.increasing ? tt : -tt, sc.towardTick, "toward tick");
            segs += his.length;
        }
        assertGt(segs, 1000);
    }
}
